---
- hosts: localhost
  become: yes
  tasks:
  - name: create ansible nodes on aws
    ec2:
     key_name: myOregonkey
     instance_type: t2.micro
     image: ami-07c8c14d081e1a07e
     wait: yes
     region: us-west-2
     group: Ansible
     count: 2
     vpc_subnet_id: subnet-69ac1611
     assign_public_ip: yes
     instance_tags:
       name: myansibleubuntunode