---
- hosts: 172.31.26.11 
  become: yes
  tasks:
  - include_task: myfile.yml

  - name: install webservers
    apt: 
      name: apache2
      state: present
      
  - name: i want restart my webserver
    service:
      name: apache2
      state: restarted
