---
- hosts: all 
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install websever on ubuntu node only
    apt:
     name: apache2
     state: present
    when: ansible_os_family=="Debian"
   