---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install websever on ubuntu node only
    apt:
     name: "{{mywebpackageforubuntu}}"
     state: present
    when: ansible_os_family=="Debian"
  
  - name: i want to install websever on RedHat node only
    yum:
      name: "{{mywebpackageforredhat}}"
      state: present
    when: ansible_os_family=="RedHat"