---
- name:  create tomcat group
  group:
    name: tomcat
    state: present
- name: create tomcat user
  user:
    name: tomcat
    home: /opt/tomcat
    shell: /bin/false
    group: tomcat
    state: present